/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ProjectJni */

#ifndef _Included_ProjectJni
#define _Included_ProjectJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ProjectJni
 * Method:    createMatrix
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ProjectJni_createMatrix
  (JNIEnv *, jobject, jint);

/*
 * Class:     ProjectJni
 * Method:    printMatrix
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_printMatrix
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ProjectJni
 * Method:    sumArray
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ProjectJni_sumArray
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ProjectJni
 * Method:    getMatrixValue
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_ProjectJni_getMatrixValue
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     ProjectJni
 * Method:    setMatrixValue
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_setMatrixValue
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     ProjectJni
 * Method:    freeMatrix
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_freeMatrix
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ProjectJni
 * Method:    createCustomString
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ProjectJni_createCustomString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ProjectJni
 * Method:    freeCString
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_freeCString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
