/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ProjectJni_Person */

#ifndef _Included_ProjectJni_Person
#define _Included_ProjectJni_Person
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ProjectJni_Person
 * Method:    createPerson
 * Signature: (JIJJJ)J
 */
JNIEXPORT jlong JNICALL Java_ProjectJni_00024Person_createPerson
  (JNIEnv *, jobject, jlong, jint, jlong, jlong, jlong);

/*
 * Class:     ProjectJni_Person
 * Method:    printPerson
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_00024Person_printPerson
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ProjectJni_Person
 * Method:    freePerson
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_00024Person_freePerson
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
