/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ProjectJni_PeopleList */

#ifndef _Included_ProjectJni_PeopleList
#define _Included_ProjectJni_PeopleList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ProjectJni_PeopleList
 * Method:    createPeopleList
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ProjectJni_00024PeopleList_createPeopleList
  (JNIEnv *, jobject);

/*
 * Class:     ProjectJni_PeopleList
 * Method:    addPerson
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_00024PeopleList_addPerson
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ProjectJni_PeopleList
 * Method:    removePerson
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_00024PeopleList_removePerson
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ProjectJni_PeopleList
 * Method:    printPeopleList
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_00024PeopleList_printPeopleList
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ProjectJni_PeopleList
 * Method:    findPersonByName
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ProjectJni_00024PeopleList_findPersonByName
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ProjectJni_PeopleList
 * Method:    updatePerson
 * Signature: (JIJIJJJ)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_00024PeopleList_updatePerson
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jlong, jlong, jlong);

/*
 * Class:     ProjectJni_PeopleList
 * Method:    freePeopleList
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ProjectJni_00024PeopleList_freePeopleList
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
